//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day7.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day7.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 2
        ///3 3
        ///4 4
        ///5 5
        ///6 6
        ///7 7
        ///8 8
        ///9 9
        ///T 10
        ///J 11
        ///Q 12
        ///K 13
        ///A 14.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 2
        ///3 3
        ///4 4
        ///5 5
        ///6 6
        ///7 7
        ///8 8
        ///9 9
        ///T 10
        ///J 1
        ///Q 12
        ///K 13
        ///A 14.
        /// </summary>
        internal static string CardsJokerVariant {
            get {
                return ResourceManager.GetString("CardsJokerVariant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A833A 309
        ///Q33J3 205
        ///55KK5 590
        ///K4457 924
        ///Q3QT3 11
        ///QJK32 349
        ///96659 162
        ///955A9 851
        ///33888 311
        ///57JJ7 721
        ///67A7A 978
        ///T44T4 557
        ///46446 802
        ///72757 471
        ///23J5J 148
        ///44944 660
        ///T89JJ 938
        ///55J55 141
        ///58858 555
        ///2Q22J 542
        ///4734Q 454
        ///22522 249
        ///Q2486 814
        ///KK3KK 577
        ///6J6KA 250
        ///9A4JJ 168
        ///72AQ7 308
        ///TJ486 320
        ///97397 121
        ///48334 748
        ///2J5J2 964
        ///4836J 588
        ///Q6565 943
        ///JAJAJ 562
        ///KK3KA 620
        ///99229 395
        ///T9T99 684
        ///22838 638
        ///7QQQ3 149
        ///6K58A 783
        ///Q3T45 675
        ///7TQ78 214
        ///A2AA5 549
        ///98944 375
        ///Q3QAA 999
        ///A8JAT 456
        ///TT9T9 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D7 {
            get {
                return ResourceManager.GetString("D7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HC 1
        ///1P 2
        ///2P 3
        ///3K 4
        ///FH 5
        ///4K 6
        ///5K 7.
        /// </summary>
        internal static string HandTypes {
            get {
                return ResourceManager.GetString("HandTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32T3K 765
        ///T55J5 684
        ///KK677 28
        ///KTJJT 220
        ///QQQJA 483.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
