//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day10.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day10.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .|-J--7F7F-F|-F777F7J-J7F--7..-LJ7F|.F7L-77--F7|7.F-7-77.F.L---J.F---FLJF-F|77-|-----|-FL-J-|7-7FF.7--F7F7.F--F7.FF-F--J-.L-L77--77|---L7--7
        ///--7-L7.FJ7--JF---7F||.LL|J-7.FJ7.-JJ--JJ.||JFJLF.FJ-|7J7L7-L7JJ|77-J||JFLJJ.LL--7JFJJJ||FL.LJ|-7FFL.FJ|F-F-|J||L-L-LJL-7LJFLJJL--F77.LF.|F|F
        ///LJ7L|.L|..LF|JF-7L-7-7|L||7L|L7-7|7FF-JL|F|-J77L7FJ.L|--J|7LJ.|F7-F7||77J7.F7|LLL.|-|---7JF7-|-7-7|FJF7..LLJLLJ..L7LL-FL7FF-LFJ.FF.-|7LJ.-L|
        ///FJF7-7.|FL-7L||-|JFJ-|JJ||7J|F7F|JFL|.J7L--7LFJ||||L.L-|.-L.LF-JJJLFJL7..F|.|7...F7--. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string D10 {
            get {
                return ResourceManager.GetString("D10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .....
        ///.S-7.
        ///.|.|.
        ///.L-J.
        ///......
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..F7.
        ///.FJ|.
        ///SJ.L7
        ///|F--J
        ///LJ....
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-F7-
        ///.FJ|7
        ///SJLL7
        ///|F--J
        ///LJ.LJ.
        /// </summary>
        internal static string Test3 {
            get {
                return ResourceManager.GetString("Test3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...........
        ///.S-------7.
        ///.|F-----7|.
        ///.||.....||.
        ///.||.....||.
        ///.|L-7.F-J|.
        ///.|..|.|..|.
        ///.L--J.L--J.
        ///............
        /// </summary>
        internal static string Test4 {
            get {
                return ResourceManager.GetString("Test4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ..........
        ///.S------7.
        ///.|F----7|.
        ///.||....||.
        ///.||....||.
        ///.|L-7F-J|.
        ///.|..||..|.
        ///.L--JL--J.
        ///...........
        /// </summary>
        internal static string Test5 {
            get {
                return ResourceManager.GetString("Test5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .F----7F7F7F7F-7....
        ///.|F--7||||||||FJ....
        ///.||.FJ||||||||L7....
        ///FJL7L7LJLJ||LJ.L-7..
        ///L--J.L7...LJS7F-7L7.
        ///....F-J..F7FJ|L7L7L7
        ///....L7.F7||L7|.L7L7|
        ///.....|FJLJ|FJ|F7|.LJ
        ///....FJL-7.||.||||...
        ///....L---J.LJ.LJLJ....
        /// </summary>
        internal static string Test6 {
            get {
                return ResourceManager.GetString("Test6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF7FSF7F7F7F7F7F---7
        ///L|LJ||||||||||||F--J
        ///FL-7LJLJ||||||LJL-77
        ///F--JF--7||LJLJ7F7FJ-
        ///L---JF-JLJ.||-FJLJJ7
        ///|F|F-JF---7F7-L7L|7|
        ///|FFJF7L7F-JF7|JL---7
        ///7-L-JL7||F7|L7F-7F7|
        ///L.L7LFJ|||||FJL7||LJ
        ///L7JLJL-JLJLJL--JLJ.L.
        /// </summary>
        internal static string Test7 {
            get {
                return ResourceManager.GetString("Test7", resourceCulture);
            }
        }
    }
}
