//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Day1.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Day1.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cmpptgjc3qhcjxcbcqgqkxhrms
        ///9sixonefour
        ///eighttwo2twofour9
        ///7eightseveneightthree
        ///tlnllks2jcfdlgsjbhpfnineone
        ///one44fivesevenjzsfzddg
        ///787seveneight75five
        ///7q7nine3
        ///hlqphphn5dtzzbqvk3three8seven
        ///ninekkbvsfq8seven7321bpdcdh
        ///9kxgfxntgdzs1ns5
        ///nineblxtnrt79t8fourbcqdzpb
        ///3mjqgthreeseven36gkvvvqppx
        ///zpcvkjjqeight94one82mrvfzdvlgjgkhj
        ///nine11
        ///rnscpccv8
        ///7eightrcqnbtkn
        ///four31zqgrccc4eight
        ///two65fourfourt1
        ///twomg2764threesix
        ///546grjcrsix9
        ///4ffourfourff1
        ///dpfkcrzjxr8four
        ///641one
        ///kseven8
        ///two4four
        ///ldzpzgch32 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Puzzle {
            get {
                return ResourceManager.GetString("Puzzle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1abc2
        ///pqr3stu8vwx
        ///a1b2c3d4e5f
        ///treb7uchet.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to two1nine
        ///eightwothree
        ///abcone2threexyz
        ///xtwone3four
        ///4nineeightseven2
        ///zoneight234
        ///7pqrstsixteen.
        /// </summary>
        internal static string Test2 {
            get {
                return ResourceManager.GetString("Test2", resourceCulture);
            }
        }
    }
}
